version: '3'
services:
  db:
    image: postgres:15-alpine
    container_name: grocerymate-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=GroceryMateDB
    ports:
      - '5433:5432'
    restart: always
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - test-network

volumes:
  db:
    driver: local

networks:
  test-network:
    driver: bridge
