version: '3.4'

services:
  db:
    image: postgres:latest
    container_name: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=ClickDB
    ports:
      - "5433:5432"
    restart: always
    volumes:
      - db:/var/lib/postgresql/data


volumes:
  db:
    driver: local