name: Frontend Build & Test

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'

      - name: Install dependencies
        run: yarn install

      - name: Build app
        run: yarn build
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Build Frontend & Backend
        run: cd .. && docker-compose -f docker-compose-dev.yml up -d 

      - name: run cypress component
        uses: cypress-io/github-action@v5
        with:
          working-directory: frontend
          install-command: yarn install
          start: yarn dev
          component: true
      - name: run cypress e2e
        if: github.base_ref == 'main'
        uses: cypress-io/github-action@v5
        with:
          working-directory: frontend
          install: false

      - uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: cypress-videos
          path: cypress/videos

