name: Frontend Build & Test

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'

      - name: Install dependencies
        run: yarn install

      - name: Build app
        run: yarn build
  codestyle:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'

      - name: Install dependencies
        run: yarn install

      - name: Run ESLint and Prettier
        run: yarn style:all

  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: run cypress component
        uses: cypress-io/github-action@v5
        with:
          working-directory: frontend
          install-command: yarn install
          start: yarn dev
          component: true
      - name: run cypress e2e
        if: github.ref == 'refs/heads/main'
        uses: cypress-io/github-action@v5
        with:
          working-directory: frontend
          install: false
          wait-on: 'http://localhost:3000'
