name: Frontend Build & Test

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./grocery-mate-frontend

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'

      - name: Install dependencies
        run: yarn install

      - name: Build app
        run: yarn build
  codestyle:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./grocery-mate-frontend

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'

      - name: Install dependencies
        run: yarn install

      - name: Run ESLint and Prettier
        run: yarn style:all

  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./grocery-mate-frontend

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'

      - name: Install dependencies
        run: yarn install

      - name: Start Cypress
        run: yarn cy:run-unit
  e2e-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./grocery-mate-frontend
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'

      - name: Install dependencies
        run: yarn install

      - name: Start Cypress
        run: yarn cy:run-e2e
